Visualization/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls", namespace="home"))
]

home/urls.py
#-*-coding:utf-8 -*-
"""
@File: urls.py
"""

from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name="index"),
    path('index/', index, name="index"),
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('search/', search, name="search"),

    # 经纬度信息操作
    path('longitudelatitude_message/', longitudelatitude_message, name="longitudelatitude_message"),
    path('longitudelatitude_detail/<int:id>', longitudelatitude_detail, name="longitudelatitude_detail"),
    path('delete_longitudelatitude_message/<int:id>', delete_longitudelatitude_message, name="delete_longitudelatitude_message"),

    # ajax 数据接口
    path('data_detail/', data_detail, name="data_detail"),
    path('get_all_message/', get_all_message, name="get_all_message"),
    path('get_message/<str:keywords>', get_message, name="get_message"),

    # 地理信息操作
    path('geographic_information/', geographic_information, name="geographic_information"),
    path('add_geographic_information/', add_geographic_information, name="add_geographic_information"),
    path('delete_geographic_information/<int:id>', delete_geographic_information, name="delete_geographic_information"),
    path('update_geographic_information/<int:id>', update_geographic_information, name="update_geographic_information"),

   # 地质信息操作
    path('geology_message/', geology_message, name="geology_message"),
    path('delete_geology_message/<int:id>', delete_geology_message, name="delete_geology_message"),
    path('update_geology_message/<int:id>', update_geology_message, name="update_geology_message"),
    path('add_geology_message/', add_geology_message, name="add_geology_message"),

    # 遥感图像匹配
    path('image_matching/', image_matching, name="image_matching"),
]

app_name = "home"


# 模拟添加数据的测试接口，可不使用
from .add_data import *
urlpatterns +=[
    # path('add_LongitudeLatitude/', add_LongitudeLatitude, name="add_LongitudeLatitude"),
    # path('add_geology/', add_geology, name="add_geology"),
    # path('add_geo_information/', add_geo_information, name="add_geo_information"),
]

home/models.py
from django.db import models


# 经纬度信息表
class LongitudeLatitude(models.Model):
    class Meta:
        verbose_name = "经纬度"
        verbose_name_plural = "经纬度"

    longitude = models.CharField(max_length=10,verbose_name="经度")
    latitude = models.CharField(max_length=10,verbose_name="纬度")


# 地质数据表
class Geology(models.Model):
    class Meta:
        verbose_name = "地质"
        verbose_name_plural = "地质"

    geology_name = models.CharField(verbose_name="地质类别", max_length=10, unique=True)
    number = models.IntegerField("编号")

    def __str__(self):
        return self.geology_name

    def __repr__(self):
        return self.geology_name


# 地理信息表
class Geographic_Information(models.Model):
    class Meta:
        verbose_name = "地理信息"
        verbose_name_plural = "地理信息"
    geology = models.ForeignKey("Geology", on_delete=models.CASCADE)
    longitudelatitude = models.ForeignKey("LongitudeLatitude", on_delete=models.CASCADE)
    depth = models.IntegerField(verbose_name="深度")

templates/common/add_geographic.html
{% extends "base.html" %}

{% block title %}
    添加地理数据
{% endblock %}

{% block style %}

{% endblock %}

{% block content %}
     <div class="content-wrapper" >
          <div class="row">
            <div class="col-md-8 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">添加地理数据</h4>
                  <p class="card-description">
                    添加地理数据，同一个经纬度中地理数据不允许重复。
                  </p>
                  <form class="forms-sample" method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                    <div class="form-group">
                    <label for="exampleFormControlSelect3">经纬度</label>
                    <select class="form-control form-control-sm" id="exampleFormControlSelect3" name="longitudelatitude" >
                        {% for foo in l_lst %}
                        <option value="{{ foo.id }}">
                            {{ foo.longitude }}/{{ foo.latitude }}
                        </option>
                        {% endfor %}
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="exampleFormControlSelect3">地质信息</label>
                    <select class="form-control form-control-sm" id="exampleFormControlSelect3" name="geology" >
                        {% for goo in g_lst %}
                        <option value="{{ goo.id }}">{{ goo.geology_name }}</option>
                        {% endfor %}
                    </select>
                  </div>
                  <div class="form-group">
                      <label for="exampleInputUsername1">深度</label>
                      <input type="number" class="form-control" name="depth" required>
                  </div>
                    <button type="submit" class="btn btn-primary btn-sm">提交</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

{% block script %}

{% endblock %}

templates/common/add_geology.html
{% extends "base.html" %}

{% block title %}
    添加地质信息
{% endblock %}

{% block style %}

{% endblock %}

{% block content %}
     <div class="content-wrapper" >
          <div class="row">
            <div class="col-md-6 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">添加地质分类</h4>
                  <p class="card-description">
                    地质类别和编号不允许重复
                  </p>
                  <form class="forms-sample" method="post" action="" enctype="multipart/form-data">
                      {% csrf_token %}
                    <div class="form-group">
                      <label for="exampleInputUsername1">类型</label>
                      <input type="text" class="form-control" name="geology_name" placeholder="geology_name" required>
                    </div>
                    <div class="form-group">
                      <label for="exampleInputUsername1">编号</label>
                      <input type="number" class="form-control" name="number" placeholder="number" required>
                    </div>
                      <div style="color: red;font-size: 12px">{{ error }}</div>
                    <button type="submit" class="btn btn-primary btn-sm">提交</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

{% block script %}

{% endblock %}

templates/common/geographic_information.html.html
{% extends "base.html" %}

{% block title %}
    地理数据信息
{% endblock %}

{% block style %}

{% endblock %}

{% block content %}
    <div class="content-wrapper">
          <div class="row">
            <div class="col-lg-12 stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">地理数据信息展示</h4>
                  <p class="card-description">
                  展示已有的<code>地理数据</code>信息，地理信息主要展示某经纬度的地质组成成分，如，土壤、矿物质等。。。
                  </p>
                  <a href="/add_geographic_information" class="btn btn-primary">添加地理信息</a>
                  <div class="table-responsive pt-3">
                    <div class="table-responsive">
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th>经纬度</th>
                          <th>地质成分</th>
                          <th>深度</th>
                          <th>占比</th>
                          <th>百分比</th>
                          <th>操作</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for datum in data %}
                            {% for l in l_list %}
                                {% if datum.longitudelatitude_id == l.longitudelatitude  %}
                        <tr>
                          <td>{{ datum.longitudelatitude.longitude }}/{{ datum.longitudelatitude.latitude }}</td>
                          <td>{{ datum.geology }}</td>
                          <td>{{ datum.depth }}（米）</td>
                          <td>
                            <div class="progress">
                              <div class="progress-bar 
                              {% if datum.geology_id == 1 %}
                              bg-success
                              {% elif datum.geology_id == 2 %}
                              bg-info
                              {% elif datum.geology_id == 3 %}
                              bg-warning
                              {% elif datum.geology_id == 4 %}
                              bg-danger
                              {% else %}
                              bg-primary
                              {% endif %}"
                                   role="progressbar" style="width: {% widthratio datum.depth l.depth__sum 100%}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                          </td>
                          <td>{{ datum.depth }}/{{ l.depth__sum }}</td>
                          <td>
                              <a href="/update_geographic_information/{{ datum.id }}" class="btn-warning btn btn-sm">编辑</a>
                              <a href="/delete_geographic_information/{{ datum.id }}" class="btn-danger btn btn-sm">删除</a>
                          </td>
                        </tr>
                                {% endif %}
                             {% endfor %}
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                  </div>
                </div>
              <ul class="list">
           {% if data.has_previous %}
            <a href="/geographic_information?page={{ data.previous_page_number }}" class="btn-sm btn">&lt;</a>
            {% endif %}
            {% for page in page_list %}
                {% if request.GET.page %}
                    {% if page == request.GET.page|add:0 %}
                        <a href="/geographic_information?page={{ page }}" class="btn-sm btn-success btn">{{ page }}</a>
                    {% elif  request.GET.page|add:0 > data.number and page == 1%}
                        <a href="/geographic_information?page={{ page }}" class="btn-sm btn-success btn">{{ page }}</a>
                    {% else %}
                        <a href="/geographic_information?page={{ page }}" class="btn-sm btn">{{ page }}</a>
                    {% endif %}
                {% else %}
                     {% if page == 1 %}
                        <a href="/geographic_information?page={{ page }}" class="btn-sm btn-success btn">{{ page }}</a>
                        {% else %}
                        <a href="/geographic_information?page={{ page }}" class="btn-sm btn">{{ page }}</a>
                     {% endif %}
                {% endif %}
            {% endfor %}
             {% if data.has_next %}
                <a href="/geographic_information?page={{ data.next_page_number }}" class="btn-sm btn">&gt;</a>
             {% endif %}
        </ul>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

{% block script %}

{% endblock %}

templates/common/geology_message.html
{% extends "base.html" %}

{% block title %}
    地址信息展示
{% endblock %}

{% block style %}

{% endblock %}

{% block content %}
    <div class="content-wrapper">
          <div class="row">
            <div class="col-lg-12 stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">经纬度信息展示</h4>
                  <p class="card-description">
                  显示已有的<code>地质</code>信息，可以对地质信息进行增、删、改操作。
                  </p>
                    <a href="/add_geology_message" class="btn btn-primary">添加地质</a>
                  <div class="table-responsive pt-3">
                    <table class="table table-bordered table-hover">
                      <thead>
                        <tr>
                          <th>编号</th>
                          <th>地质类别</th>
                          <th>操作</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for geology in data %}
                        <tr class="table">
                          <td>{{ geology.number }}</td>
                          <td>{{ geology.geology_name }}</td>
                          <td>
                              <a href="/update_geology_message/{{ geology.id }}" class="btn-sm btn btn-success">编辑</a>
                              <a href="/delete_geology_message/{{ geology.id }}" class="btn-sm btn btn-danger">删除</a>
                          </td>
                        </tr>
                      {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              <ul class="list">
           {% if data.has_previous %}
            <a href="/geology_message?page={{ data.previous_page_number }}" class="btn-sm btn">&lt;</a>
            {% endif %}
            {% for page in page_list %}
                {% if request.GET.page %}
                    {% if page == request.GET.page|add:0 %}
                        <a href="/geology_message?page={{ page }}" class="btn-sm btn-success btn">{{ page }}</a>
                    {% elif  request.GET.page|add:0 > data.number and page == 1%}
                        <a href="/geology_message?page={{ page }}" class="btn-sm btn-success btn">{{ page }}</a>
                    {% else %}
                        <a href="/geology_message?page={{ page }}" class="btn-sm btn">{{ page }}</a>
                    {% endif %}
                {% else %}
                     {% if page == 1 %}
                        <a href="/geology_message?page={{ page }}" class="btn-sm btn-success btn">{{ page }}</a>
                        {% else %}
                        <a href="/geology_message?page={{ page }}" class="btn-sm btn">{{ page }}</a>
                     {% endif %}
                {% endif %}
            {% endfor %}
             {% if data.has_next %}
                <a href="/geology_message?page={{ data.next_page_number }}" class="btn-sm btn">&gt;</a>
             {% endif %}
        </ul>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

{% block script %}

{% endblock %}

templates/common/image_matching.html
{% extends "base.html" %}

{% block title %}
    首页
{% endblock %}

{% block style %}
    
{% endblock %}
{% block search %}
    
{% endblock %}
{% block content %}
    <div class="content-wrapper">
           <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                <img src="/static/images/auth/lockscreen-bg.jpg" style="width: 700px;height: 550px" alt="">
                </div>
              </div>
            </div>
          </div>
           <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                    <form action="">
                        <button class="btn btn-success btn-sm">匹配</button>
                        <a href="/image_matching" class="btn btn-warning btn-sm">重新匹配</a>
                    </form>
                </div>
              </div>
            </div>
          </div>
    </div>
{% endblock %}

{% block script %}

{% endblock %}

templates/common/index.html
{% extends "base.html" %}

{% block title %}
    首页
{% endblock %}

{% block style %}
    <script src="/static/echarts/jquery-2.1.1.min.js"></script>
    <script src="/static/echarts/echarts.min.js"></script>
    <script src="/static/echarts/echarts_gl.js"></script>
{% endblock %}
{% block search %}
    <form action="/search" method="get">
    <div class="navbar-menu-wrapper navbar-search-wrapper d-none d-lg-flex align-items-center">
        <ul class="navbar-nav mr-lg-2">
          <li class="nav-item nav-search d-none d-lg-block">
          <div class="input-group">
            <input type="text" name="keywords" class="form-control" placeholder="请输入经度" aria-label="search" aria-describedby="search">

          </div>
        </li>
      </ul>
       <ul class="navbar-nav navbar-nav-right">
        <li class="nav-item nav-profile dropdown">
            <button class="btn btn-primary" type="submit">搜索</button>
        </li>
      </ul>
    </div>
    </form>
{% endblock %}
{% block content %}
    <div class="content-wrapper">
           <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                <div style="width: 700px;height: 550px" id="main" ></div>
                <script>
                    $.ajax({
                        url:"/get_all_message",
                        type:"get",
                        dataType:"json",
                        success:function (data) {
                          f(data.data);
                        }
                      });
                    function f(data) {
                    var Mychart =  echarts.init(document.getElementById("main"));
                    var option = {
                    title: {
                        text: '地理数据在经纬度的分布图',
                        left: 'center',
                        top: 0
                    },
                    visualMap: {
                        show:false,
                        min: 15202,
                        max: 159980,
                        dimension: 1,
                        orient: 'vertical',
                        right: 10,
                        top: 'center',
                        text: ['HIGH', 'LOW'],
                        calculable: true,
                        inRange: {
                            color: ['#f2c31a', '#24b7f2']
                        }
                    },
                    tooltip: {
                        trigger: 'item',
                        axisPointer: {
                            type: 'cross'
                        }
                    },
                    xAxis: [{
                        type: 'value'
                    }],
                    yAxis: [{
                        type: 'value'
                    }],
                    series: [{
                        name: '探测深度',
                        type: 'scatter',
                        symbolSize: 5,
                        // itemStyle: {
                        //     normal: {
                        //         borderWidth: 0.2,
                        //         borderColor: '#fff'
                        //     }
                        // },
                        data: data
                    }]
                    };
                    Mychart.setOption(option);
                    }
                </script>
                </div>
              </div>
            </div>
          </div>
           <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                本网站主要展示经纬度的地质信息，目前收录了1800条经纬度信息，提供了对应的地质信息更新功能，在以后可以对地质信息进行更新。
                </div>
              </div>
            </div>
          </div>
    </div>
{% endblock %}

{% block script %}

{% endblock %}

templates/common/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>地理及地质数据可视化系统</title>
  <!-- base:css -->
  <link rel="stylesheet" href="/static/vendors/mdi/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="/static/vendors/css/vendor.bundle.base.css">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="/static/css/style.css">
  <!-- endinject -->
  <link rel="shortcut icon" href="/static/images/favicon.png" />
</head>

<body>
  <div class="container-scroller d-flex">
    <div class="container-fluid page-body-wrapper full-page-wrapper d-flex">
      <div class="content-wrapper d-flex align-items-center auth px-0">
        <div class="row w-100 mx-0">
          <div class="col-lg-4 mx-auto">
            <div class="auth-form-light text-left py-5 px-4 px-sm-5">
              <div class="brand-logo">
                <img src="/static/images/logo.svg" alt="logo">
              </div>
              <h4>地理及地质数据可视化系统</h4>
              <h6 class="font-weight-light">请登录...</h6>
              <form class="pt-3" method="post">
                  {% csrf_token %}
                <div class="form-group">
                  <input type="text" class="form-control form-control-lg"  placeholder="username" name="username">
                </div>
                <div class="form-group">
                  <input type="password" class="form-control form-control-lg"  placeholder="password" name="password">
                </div>
                  <div style="color: red">{{ error }}</div>
                <div class="mt-3">
                  <button class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn" >登录</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- base:js -->
  <script src="/static/vendors/js/vendor.bundle.base.js"></script>
  <!-- endinject -->
  <!-- inject:js -->
  <script src="/static/js/off-canvas.js"></script>
  <script src="/static/js/hoverable-collapse.js"></script>
  <script src="/static/js/template.js"></script>
  <!-- endinject -->
</body>

</html>

templates/common/longitudelatitude_detail.html
{% extends "base.html" %}

{% block title %}
    {{ longitudelatitude.longitude }}/{{ longitudelatitude.latitude }}详情
{% endblock %}

{% block style %}

{% endblock %}

{% block content %}
    <input type="hidden" id="longitudelatitude_id" value="{{ longitudelatitude.id }}">
    <div class="content-wrapper">
          <div class="row">
            <div class="col-lg-6 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">折线图</h4>
                  <canvas id="areaChart"></canvas>
                </div>
              </div>
            </div>
              <div class="col-lg-6 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">柱状图</h4>
                  <canvas id="barChart"></canvas>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-8 grid-margin grid-margin-lg-0 stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">饼状图</h4>
                  <canvas id="pieChart"></canvas>
                </div>
              </div>
            </div>

          </div>
        </div>
{% endblock %}

{% block script %}
    <script src="/static/echarts/chart.js"></script>
{% endblock %}

templates/common/longitudelatitude_message.html
{% extends "base.html" %}

{% block title %}
    经纬度信息展示
{% endblock %}

{% block style %}

{% endblock %}

{% block content %}
    <div class="content-wrapper">
          <div class="row">
            <div class="col-lg-12 stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">经纬度信息展示</h4>
                  <p class="card-description">
                  这里显示已存在的<code>经纬</code>度信息，可对经纬度信息进行删除操作
                  </p>
                  <div class="table-responsive pt-3">
                    <table class="table table-bordered table-hover">
                      <thead>
                        <tr>
                          <th>经度</th>
                          <th>纬度</th>
                          <th>已有地理信息</th>
                          <th>详细信息</th>
                          <th>操作</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for longitudelatitude in data %}
                        <tr class="table">
                          <td>{{ longitudelatitude.longitude }}</td>
                          <td>{{ longitudelatitude.latitude }}</td>
                          <td>{{ longitudelatitude.geographic_information_set.all.count }}(条)</td>
                          <td><a href="/longitudelatitude_detail/{{ longitudelatitude.id }}" class="btn btn-success btn-sm">查看详情</a></td>
                          <td><a href="/delete_longitudelatitude_message/{{ longitudelatitude.id }}" class="btn btn-danger btn-sm">删除</a></td>
                        </tr>
                      {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              <ul class="list">
           {% if data.has_previous %}
            <a href="/longitudelatitude_message?page={{ data.previous_page_number }}" class="btn-sm btn">&lt;</a>
            {% endif %}
            {% for page in page_list %}
                {% if request.GET.page %}
                    {% if page == request.GET.page|add:0 %}
                        <a href="/longitudelatitude_message?page={{ page }}" class="btn-sm btn-success btn">{{ page }}</a>
                    {% elif  request.GET.page|add:0 > data.number and page == 1%}
                        <a href="/longitudelatitude_message?page={{ page }}" class="btn-sm btn-success btn">{{ page }}</a>
                    {% else %}
                        <a href="/longitudelatitude_message?page={{ page }}" class="btn-sm btn">{{ page }}</a>
                    {% endif %}
                {% else %}
                     {% if page == 1 %}
                        <a href="/longitudelatitude_message?page={{ page }}" class="btn-sm btn-success btn">{{ page }}</a>
                        {% else %}
                        <a href="/longitudelatitude_message?page={{ page }}" class="btn-sm btn">{{ page }}</a>
                     {% endif %}
                {% endif %}
            {% endfor %}
             {% if data.has_next %}
                <a href="/longitudelatitude_message?page={{ data.next_page_number }}" class="btn-sm btn">&gt;</a>
             {% endif %}
        </ul>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

{% block script %}

{% endblock %}

templates/common/update_geographic.html
{% extends "base.html" %}

{% block title %}
    编辑地理数据
{% endblock %}

{% block style %}

{% endblock %}

{% block content %}
     <div class="content-wrapper" >
          <div class="row">
            <div class="col-md-8 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">编辑地理数据</h4>
                  <p class="card-description">
                    编辑地理数据，同一个经纬度中地理数据不允许重复。
                  </p>
                  <form class="forms-sample" method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                    <div><input type="hidden" name="id" value="{{ geographic.id }}"></div>
                    <div class="form-group">
                    <label for="exampleFormControlSelect3">经纬度</label>
                    <select class="form-control form-control-sm" id="exampleFormControlSelect3" name="longitudelatitude" >
                        {% for foo in l_lst %}
                        <option value="{{ foo.id }}"
                                {% if geographic.longitudelatitude_id == foo.id %}
                        selected
                        {% endif %}>
                            {{ foo.longitude }}/{{ foo.latitude }}
                        </option>
                        {% endfor %}
                    </select>
                  </div>
                    <div class="form-group">
                    <label for="exampleFormControlSelect3">地质信息</label>
                    <select class="form-control form-control-sm" id="exampleFormControlSelect3" name="geology" >
                        {% for goo in g_lst %}
                        <option value="{{ goo.id }}" {% if goo.id == geographic.geology_id %}
                        selected
                        {% endif %}>{{ goo.geology_name }}</option>
                        {% endfor %}
                    </select>
                  </div>
                    <div class="form-group">
                      <label for="exampleInputUsername1">深度</label>
                      <input type="number" class="form-control" name="depth" value="{{ geographic.depth }}" required>
                    </div>
                    <button type="submit" class="btn btn-primary btn-sm">提交</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

{% block script %}

{% endblock %}

templates/common/update_geology.html
{% extends "base.html" %}

{% block title %}
    添加地质信息
{% endblock %}

{% block style %}

{% endblock %}

{% block content %}
     <div class="content-wrapper" >
          <div class="row">
            <div class="col-md-6 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">编辑地质分类</h4>
                  <p class="card-description">
                    地质类别和编号不允许重复
                  </p>
                  <form class="forms-sample" method="post" action="" enctype="multipart/form-data">
                      {% csrf_token %}
                      <input type="hidden" name="id" value="{{ geology.id}}">
                    <div class="form-group">
                      <label for="exampleInputUsername1">类型</label>
                      <input type="text" class="form-control" name="geology_name" placeholder="geology_name" value="{{ geology.geology_name }}" required>
                    </div>
                    <div class="form-group">
                      <label for="exampleInputUsername1">编号</label>
                      <input type="number" class="form-control" name="number" placeholder="number" value="{{ geology.number }}" required>
                    </div>
                      <div style="color: red;font-size: 12px">{{ error }}</div>
                    <button type="submit" class="btn btn-primary btn-sm">提交</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

{% block script %}

{% endblock %}